import { Product as ProductType } from '@/types';
import { formatPrice as formatPriceUtil } from '@/lib/utils';

export type { ProductType as Product };

export const formatPrice = formatPriceUtil;

export const products: ProductType[] = [
  {
    id: '1',
    slug: 'reloj-clasico-dorado',
    name: 'Reloj Clásico Dorado',
    description: 'Reloj clásico con correa de acero inoxidable y esfera dorada. Resistente al agua hasta 50m.',
    short_description: 'Reloj clásico con correa de acero inoxidable.',
    price: 189900,
    compare_at_price: 249900,
    cost_price: null,
    sku: 'RCD-001',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 50,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-1', product_id: '1', url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=533&fit=crop', alt: 'Reloj Clásico Dorado', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'hombre',
    brand_id: 'casio',
    tags: ['reloj', 'hombre', 'dorado'],
    featured: true,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'reloj-deportivo-negro',
    name: 'Reloj Deportivo Negro',
    description: 'Reloj deportivo con GPS y monitor de ritmo cardíaco. Perfecto para entrenamientos.',
    short_description: 'Reloj deportivo con GPS.',
    price: 229900,
    compare_at_price: 299900,
    cost_price: null,
    sku: 'RDN-002',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 30,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-2', product_id: '2', url: 'https://images.unsplash.com/photo-1557438159-51eec7a6c9e8?w=400&h=533&fit=crop', alt: 'Reloj Deportivo Negro', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'hombre',
    brand_id: 'nike',
    tags: ['reloj', 'hombre', 'deportivo'],
    featured: true,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'reloj-elegante-mujer',
    name: 'Reloj Elegante Mujer',
    description: 'Reloj elegante con pulsera de cerámica y cristales Swarovski.',
    short_description: 'Reloj elegante con cristales Swarovski.',
    price: 349900,
    compare_at_price: null,
    cost_price: null,
    sku: 'REM-003',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 20,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-3', product_id: '3', url: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400&h=533&fit=crop', alt: 'Reloj Elegante Mujer', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'mujer',
    brand_id: null,
    tags: ['reloj', 'mujer', 'elegante'],
    featured: true,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'cadena-acero-premium',
    name: 'Cadena de Acero Premium',
    description: 'Cadena de acero inoxidable con baño de plata.',
    short_description: 'Cadena de acero inoxidable.',
    price: 89900,
    compare_at_price: 119900,
    cost_price: null,
    sku: 'CAP-004',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 40,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-4', product_id: '4', url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=533&fit=crop', alt: 'Cadena de Acero Premium', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'accesorios',
    brand_id: 'pandora',
    tags: ['cadena', 'accesorio', 'acero'],
    featured: false,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'pulsera-cuero-artesanal',
    name: 'Pulsera de Cuero Artesanal',
    description: 'Pulsera de cuero genuino con cierre de acero.',
    short_description: 'Pulsera de cuero genuino.',
    price: 59900,
    compare_at_price: null,
    cost_price: null,
    sku: 'PCA-005',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 60,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-5', product_id: '5', url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=533&fit=crop', alt: 'Pulsera de Cuero Artesanal', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'accesorios',
    brand_id: null,
    tags: ['pulsera', 'accesorio', 'cuero'],
    featured: false,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'reloj-smart-watch',
    name: 'Reloj Smart Watch',
    description: 'Smartwatch con pantalla AMOLED, GPS y resistencia al agua IP68.',
    short_description: 'Smartwatch con pantalla AMOLED.',
    price: 459900,
    compare_at_price: 549900,
    cost_price: null,
    sku: 'RSW-006',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 25,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-6', product_id: '6', url: 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=400&h=533&fit=crop', alt: 'Reloj Smart Watch', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'hombre',
    brand_id: 'samsung',
    tags: ['smartwatch', 'hombre', 'tecnologia'],
    featured: true,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'anillo-plata-925',
    name: 'Anillo de Plata 925',
    description: 'Anillo de plata 925 con cristal Swarovski.',
    short_description: 'Anillo de plata 925.',
    price: 129900,
    compare_at_price: null,
    cost_price: null,
    sku: 'AP9-007',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 35,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-7', product_id: '7', url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=533&fit=crop', alt: 'Anillo de Plata 925', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'accesorios',
    brand_id: 'swarovski',
    tags: ['anillo', 'accesorio', 'plata'],
    featured: false,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    slug: 'reloj-mujer-rosa-gold',
    name: 'Reloj Mujer Rosa Gold',
    description: 'Reloj con correa de malla y caja en color rosa gold.',
    short_description: 'Reloj en color rosa gold.',
    price: 279900,
    compare_at_price: 329900,
    cost_price: null,
    sku: 'RMG-008',
    barcode: null,
    track_inventory: false,
    inventory_quantity: 28,
    allow_backorder: false,
    weight: null,
    dimensions: null,
    images: [
      { id: 'img-8', product_id: '8', url: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=533&fit=crop', alt: 'Reloj Mujer Rosa Gold', position: 0, created_at: new Date().toISOString() },
    ],
    category_id: 'mujer',
    brand_id: 'fossil',
    tags: ['reloj', 'mujer', 'rosa-gold'],
    featured: true,
    status: 'active',
    seo_title: null,
    seo_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function getProductById(id: string): ProductType | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category: string): ProductType[] {
  return products.filter(p => p.category_id === category);
}